### ISSUE TITLE
Top bar is misplaced Chrome/Chromium on Arch Linux

### ISSUE THREAD

**Issue by MegaLoler** [ariankordi/closedverse#8] opened 2018-05-23 14:56 UTC
![image](https://user-images.githubusercontent.com/4969196/40432036-574b61c2-5e6e-11e8-9022-57a918585565.png)

i get this happening when using Chromium Version 66.0.3359.170 (Official Build) Arch Linux (64-bit) (it happens with Google Chrome on this same machine as well)
it doesn't happen on Firefox on this machine, and it doesn't happen with Google Chrome on my Windows 10

**Comment by MegaLoler** [comment] 2018-05-23 15:07
here's a proposed solution:
in static/closedverse.css:
```css
#global-menu li {
  float: left;
  padding: 0 10px;
  line-height: 1;
  padding-left: 1px; /* this line */
}
```

**Comment by ariankordi** [comment] 2023-05-15 01:29
for the purpose of closing this issue: if it's not obvious, this is because the font is wider than expected, it can be reproduced by inspect elementing to make the text longer on one of the menu titles there. supposedly you could just expand the entire menu area since the browser is wide enough for that, but i don t care enough for that and so don't you
rip closed worse

**Closed as not planned** 2023-05-15 01:29 UTC
